// This file is generated by Slice Machine. Update with care!

import AccordionSlice from './AccordionSlice'
import AuthorsListSlice from './AuthorsListSlice'
import AwardsSlice from './AwardsSlice'
import BenefitSlice from './BenefitSlice'
import BuildAndRisksSlice from './BuildAndRisksSlice'
import ButtonSlice from './ButtonSlice'
import CardGridSlice from './CardGridSlice'
import CardWithImageSlice from './CardWithImageSlice'
import CardsWithIcon from './CardsWithIcon'
import CaseListSlice from './CaseListSlice'
import CasesListSlice from './CasesListSlice'
import ContactsSlice from './ContactsSlice'
import CreateProjectsSlice from './CreateProjectsSlice'
import CtaBannerSlice from './CtaBannerSlice'
import CustomerLogoSlice from './CustomerLogoSlice'
import CustomerRatesSlice from './CustomerRatesSlice'
import CustomerTestimonials from './CustomerTestimonials'
import DescriptionSliceWithIcon from './DescriptionSliceWithIcon'
import EbookPageCardsSlice from './EbookPageCardsSlice'
import EbooksWithFilterSlice from './EbooksWithFilterSlice'
import EmbedSlice from './EmbedSlice'
import FormSlice from './FormSlice'
import GridLottieSlice from './GridLottieSlice'
import ImageSlice from './ImageSlice'
import ImageWithCaption from './ImageWithCaption'
import KeyMetricsSlice from './KeyMetricsSlice'
import NavLinkSlice from './NavLinkSlice'
import PostsSectionSlice from './PostsSectionSlice'
import PressCenter from './PressCenter'
import ProgressSlice from './ProgressSlice'
import ProjectStartSlice from './ProjectStartSlice'
import QuickProjectStart from './QuickProjectStart'
import SingleImage from './SingleImage'
import SpacerSlice from './SpacerSlice'
import StartScreen from './StartScreen'
import TeamCards from './TeamCards'
import TechnologiesAndTools from './TechnologiesAndTools'
import TechnologiesSlice from './TechnologiesSlice'
import TextList from './TextList'
import TextSlice from './TextSlice'
import TitleAndParagraphSlice from './TitleAndParagraphSlice'
import VideoSlice from './VideoSlice'
import WeCreateProjectsFor from './WeCreateProjectsFor'

export {
  AccordionSlice,
  AuthorsListSlice,
  AwardsSlice,
  BenefitSlice,
  BuildAndRisksSlice,
  ButtonSlice,
  CardGridSlice,
  CardWithImageSlice,
  CardsWithIcon,
  CaseListSlice,
  CasesListSlice,
  ContactsSlice,
  CreateProjectsSlice,
  CtaBannerSlice,
  CustomerLogoSlice,
  CustomerRatesSlice,
  CustomerTestimonials,
  DescriptionSliceWithIcon,
  EbookPageCardsSlice,
  EbooksWithFilterSlice,
  EmbedSlice,
  FormSlice,
  GridLottieSlice,
  ImageSlice,
  ImageWithCaption,
  KeyMetricsSlice,
  NavLinkSlice,
  PostsSectionSlice,
  PressCenter,
  ProgressSlice,
  ProjectStartSlice,
  QuickProjectStart,
  SingleImage,
  SpacerSlice,
  StartScreen,
  TeamCards,
  TechnologiesAndTools,
  TechnologiesSlice,
  TextList,
  TextSlice,
  TitleAndParagraphSlice,
  VideoSlice,
  WeCreateProjectsFor,
}

export const components = {
  accordion_slice: AccordionSlice,
  authors_list_slice: AuthorsListSlice,
  awards_slice: AwardsSlice,
  benefit_slice: BenefitSlice,
  build_and_risks_slice: BuildAndRisksSlice,
  button_slice: ButtonSlice,
  card_grid_slice: CardGridSlice,
  card_with_image_slice: CardWithImageSlice,
  cards_with_icon: CardsWithIcon,
  case_list_slice: CaseListSlice,
  cases_list_slice: CasesListSlice,
  contacts_slice: ContactsSlice,
  create_projects_slice: CreateProjectsSlice,
  cta_banner_slice: CtaBannerSlice,
  customer_logo_slice: CustomerLogoSlice,
  customer_rates_slice: CustomerRatesSlice,
  customer_testimonials: CustomerTestimonials,
  description_slice_with_icon: DescriptionSliceWithIcon,
  ebook_page_cards_slice: EbookPageCardsSlice,
  ebooks_with_filter_slice: EbooksWithFilterSlice,
  embed_slice: EmbedSlice,
  form_slice: FormSlice,
  grid_lottie_slice: GridLottieSlice,
  image_slice: ImageSlice,
  image_with_caption: ImageWithCaption,
  key_metrics_slice: KeyMetricsSlice,
  nav_link_slice: NavLinkSlice,
  posts_section_slice: PostsSectionSlice,
  press_center: PressCenter,
  progress_slice: ProgressSlice,
  project_start_slice: ProjectStartSlice,
  quick_project_start: QuickProjectStart,
  single_image: SingleImage,
  spacer_slice: SpacerSlice,
  start_screen: StartScreen,
  team_cards: TeamCards,
  technologies_and_tools: TechnologiesAndTools,
  technologies_slice: TechnologiesSlice,
  text_list: TextList,
  text_slice: TextSlice,
  title_and_paragraph_slice: TitleAndParagraphSlice,
  video_slice: VideoSlice,
  we_create_projects_for: WeCreateProjectsFor,
}
