const dotenv = require('dotenv')

dotenv.config()

// Atlassian
const ATLASSIAN_TOKEN = process.env.NODE_ATLASSIAN_TOKEN
const ATLASSIAN_EMAIL = process.env.NODE_ATLASSIAN_EMAIL
const ATLASSIAN_AUTH_TOKEN = `${ATLASSIAN_EMAIL}:${ATLASSIAN_TOKEN}`
const ATLASSIAN_PROJECT_KEY = process.env.NODE_ATLASSIAN_PROJECT_KEY
const ATLASSIAN_API_URL = process.env.NODE_ATLASSIAN_API_URL
const ATLASSIAN_PROJECT_EBOOK_KEY = process.env.NODE_ATLASSIAN_EBOOK_PROJECT_KEY
const ATLASSIAN_SUBSCRIBERS_PROJECT_KEY = process.env.NODE_ATLASSIAN_SUBSCRIBERS_PROJECT_KEY

// Send pulse
const SENDPULSE_API_KEY = process.env.NODE_SENDPULSE_API_KEY
const SENDPULSE_API_USER_ID = process.env.NODE_SENDPULSE_API_USER_ID
const SENDPULSE_TOKEN_STORAGE = '/tmp/'

// Huntflow
const HUNTFLOW_TOKEN = process.env.NODE_HUNTFLOW_TOKEN
const HUNTFLOW_API_URL = process.env.NODE_HUNTFLOW_API_URL
const HUNTFLOW_ACCOUNT_ID = process.env.NODE_HUNTFLOW_ACCOUNT_ID
const HUNTFLOW_RESERVE_VACANCY_ID = process.env.NODE_HUNTFLOW_RESERVE_VACANCY_ID

// Sentry
const SENTRY_DSN = process.env.NODE_SENTRY_DSN

// Other
const { NODE_ENV } = process.env

// S3
const S3_ACCESS_KEY_ID = process.env.NODE_S3_ACCESS_KEY_ID
const S3_SECRET_ACCESS_KEY = process.env.NODE_S3_SECRET_ACCESS_KEY

// IP
const IP_INFO_TOKEN = process.env.NODE_IP_INFO_TOKEN
const IP_BAN_LIST = process.env.NODE_IP_BAN_LIST
const IP_TEST_LIST = process.env.NODE_IP_TEST_LIST
const TEST_EMAIL = process.env.NODE_TEST_EMAIL

// Prismic
const PRISMIC_API = process.env.NODE_PRISMIC_API

// reCaptcha key
const RECAPTCHA_KEY = process.env.RECAPTCHA_SECRET_KEY

// Radiator
const DEV_RADIATOR_SLACK_WEBHOOK = process.env.NODE_DEV_RADIATOR_SLACK_WEBHOOK
const DEV_RADIATOR_GH_TOKEN = process.env.NODE_DEV_RADIATOR_GH_TOKEN
const DEV_RADIATOR_PAGESPEED_MEASUREMENTS_COUNT = process.env.NODE_DEV_RADIATOR_PAGESPEED_MEASUREMENTS_COUNT
const DEV_RADIATOR_COLLECT_DATA_CRON_STRING = process.env.NODE_DEV_RADIATOR_COLLECT_DATA_CRON_STRING
const DEV_RADIATOR_SEND_MESSAGE_CRON_STRING = process.env.NODE_DEV_RADIATOR_SEND_MESSAGE_CRON_STRING
const DEV_RADIATOR_MONGO = process.env.NODE_DEV_RADIATOR_MONGO

const GOOGLEAPIS_KEY = process.env.NODE_GOOGLEAPIS_KEY

// mad radiator
const MAD_RADIATOR_AUTH_TYPE = process.env.RADIATOR_AUTH_TYPE
const MAD_RADIATOR_AUTH_URI = process.env.RADIATOR_AUTH_URI
const MAD_RADIATOR_CLIENT_CERT_URL = process.env.RADIATOR_CLIENT_CERT_URL
const MAD_RADIATOR_CLIENT_EMAIL = process.env.RADIATOR_CLIENT_EMAIL
const MAD_RADIATOR_CLIENT_ID = process.env.RADIATOR_CLIENT_ID
const MAD_RADIATOR_GOOGLEAPIS_KEY = process.env.NODE_GOOGLEAPIS_KEY
const MAD_RADIATOR_PRIVATE_KEY = process.env.RADIATOR_PRIVATE_KEY
const MAD_RADIATOR_PRIVATE_KEY_ID = process.env.RADIATOR_PRIVATE_KEY_ID
const MAD_RADIATOR_PROJECT_ID = process.env.RADIATOR_PROJECT_ID
const MAD_RADIATOR_PROVIDER_CERT_URL = process.env.RADIATOR_PROVIDER_CERT_URL
const MAD_RADIATOR_TOKEN_URI = process.env.RADIATOR_TOKEN_URI
const MAD_RADIATOR_SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL
const MAD_RADIATOR_SLACK_CHANNEL_ID = process.env.SLACK_CHANNEL_ID
const MAD_RADIATOR_REDDIT_CLIENT_ID = process.env.REDDIT_CLIENT_ID
const MAD_RADIATOR_REDDIT_CLIENT_SECRET = process.env.REDDIT_CLIENT_SECRET
const MAD_RADIATOR_REDDIT_USER_NAME = process.env.REDDIT_USER_NAME
const MAD_RADIATOR_REDDIT_PASSWORD = process.env.REDDIT_PASSWORD
const MAD_RADIATOR_QUORA_USER_ID = process.env.RADIATOR_QUORA_USER_ID
const MAD_RADIATOR_DAILY_DISPATCH_TIME = process.env.RADIATOR_DAILY_DISPATCH_TIME
const MAD_RADIATOR_FIRESTORE_AUTH_TYPE = process.env.RADIATOR_FIRESTORE_AUTH_TYPE
const MAD_RADIATOR_FIRESTORE_PROJECT_ID = process.env.RADIATOR_FIRESTORE_PROJECT_ID
const MAD_RADIATOR_FIRESTORE_PRIVATE_KEY_ID = process.env.RADIATOR_FIRESTORE_PRIVATE_KEY_ID
const MAD_RADIATOR_FIRESTORE_PRIVATE_KEY = process.env.RADIATOR_FIRESTORE_PRIVATE_KEY
const MAD_RADIATOR_FIRESTORE_CLIENT_EMAIL = process.env.RADIATOR_FIRESTORE_CLIENT_EMAIL
const MAD_RADIATOR_FIRESTORE_CLIENT_ID = process.env.RADIATOR_FIRESTORE_CLIENT_ID
const MAD_RADIATOR_FIRESTORE_AUTH_URI = process.env.RADIATOR_FIRESTORE_AUTH_URI
const MAD_RADIATOR_FIRESTORE_TOKEN_URI = process.env.RADIATOR_FIRESTORE_TOKEN_URI
const MAD_RADIATOR_FIRESTORE_AUTH_PROVIDER = process.env.RADIATOR_FIRESTORE_AUTH_PROVIDER
const MAD_RADIATOR_FIRESTORE_CLIENT_CERT_URL = process.env.RADIATOR_FIRESTORE_CLIENT_CERT_URL

// to send email from ebook form
const EMAIL_NODE_EMAIL_MARKETING = process.env.NODE_EMAIL_MARKETING

module.exports = {
  ATLASSIAN_TOKEN,
  ATLASSIAN_EMAIL,
  ATLASSIAN_AUTH_TOKEN,
  ATLASSIAN_PROJECT_KEY,
  ATLASSIAN_API_URL,
  ATLASSIAN_PROJECT_EBOOK_KEY,
  ATLASSIAN_SUBSCRIBERS_PROJECT_KEY,
  SENDPULSE_API_USER_ID,
  SENDPULSE_API_KEY,
  SENDPULSE_TOKEN_STORAGE,
  HUNTFLOW_TOKEN,
  HUNTFLOW_API_URL,
  HUNTFLOW_ACCOUNT_ID,
  HUNTFLOW_RESERVE_VACANCY_ID,
  SENTRY_DSN,
  NODE_ENV,
  S3_ACCESS_KEY_ID,
  S3_SECRET_ACCESS_KEY,
  IP_INFO_TOKEN,
  IP_BAN_LIST,
  IP_TEST_LIST,
  TEST_EMAIL,
  PRISMIC_API,
  RECAPTCHA_KEY,
  DEV_RADIATOR_SLACK_WEBHOOK,
  DEV_RADIATOR_GH_TOKEN,
  DEV_RADIATOR_COLLECT_DATA_CRON_STRING,
  DEV_RADIATOR_SEND_MESSAGE_CRON_STRING,
  DEV_RADIATOR_MONGO,
  GOOGLEAPIS_KEY,
  DEV_RADIATOR_PAGESPEED_MEASUREMENTS_COUNT,
  MAD_RADIATOR_AUTH_TYPE,
  MAD_RADIATOR_AUTH_URI,
  MAD_RADIATOR_CLIENT_CERT_URL,
  MAD_RADIATOR_CLIENT_EMAIL,
  MAD_RADIATOR_CLIENT_ID,
  MAD_RADIATOR_GOOGLEAPIS_KEY,
  MAD_RADIATOR_PRIVATE_KEY,
  MAD_RADIATOR_PRIVATE_KEY_ID,
  MAD_RADIATOR_PROJECT_ID,
  MAD_RADIATOR_PROVIDER_CERT_URL,
  MAD_RADIATOR_TOKEN_URI,
  MAD_RADIATOR_SLACK_WEBHOOK_URL,
  MAD_RADIATOR_SLACK_CHANNEL_ID,
  MAD_RADIATOR_REDDIT_CLIENT_ID,
  MAD_RADIATOR_REDDIT_CLIENT_SECRET,
  MAD_RADIATOR_REDDIT_USER_NAME,
  MAD_RADIATOR_REDDIT_PASSWORD,
  MAD_RADIATOR_QUORA_USER_ID,
  MAD_RADIATOR_DAILY_DISPATCH_TIME,
  EMAIL_NODE_EMAIL_MARKETING,
  MAD_RADIATOR_FIRESTORE_AUTH_TYPE,
  MAD_RADIATOR_FIRESTORE_PROJECT_ID,
  MAD_RADIATOR_FIRESTORE_PRIVATE_KEY_ID,
  MAD_RADIATOR_FIRESTORE_PRIVATE_KEY,
  MAD_RADIATOR_FIRESTORE_CLIENT_EMAIL,
  MAD_RADIATOR_FIRESTORE_CLIENT_ID,
  MAD_RADIATOR_FIRESTORE_AUTH_URI,
  MAD_RADIATOR_FIRESTORE_TOKEN_URI,
  MAD_RADIATOR_FIRESTORE_AUTH_PROVIDER,
  MAD_RADIATOR_FIRESTORE_CLIENT_CERT_URL,
}
